accounts:
  - id: "1e7ed1e7e9b2dfdfb15ed609d30fbe52"
    name: "Yet another Cloudflare account"
    lists:
      - name: "bad_ips"
        sync_from: "https://github.com/stamparm/ipsum/raw/refs/heads/master/levels/3.txt"
    notifications:
      webhook: "https://yet-another-webhook-url.com"
      telegram_bot_token: "123456789:ABCDEF1234567890"
      telegram_chat_id: "-1001122334455"
