accounts:
  - id: "1e7ed1e7e9b2dfdfb15ed609d30fbe52"
    name: "Yet Another Cloudflare Account"
    lists:
      # --- Major Cloud Providers (Only AWS & Azure Active) ---
      # - name: "trusted_aws_ips"
      #   sync_from: "https://raw.githubusercontent.com/lord-alfred/ipranges/main/aws.json"
      #   type: "json"

      # - name: "trusted_azure_ips"
      #   sync_from: "https://raw.githubusercontent.com/lord-alfred/ipranges/main/azure.json"
      #   type: "json"

      # - name: "trusted_gcp_ips"
      #   sync_from: "https://raw.githubusercontent.com/lord-alfred/ipranges/main/gcp.json"
      #   type: "json"

      # - name: "trusted_oracle_ips"
      #   sync_from: "https://raw.githubusercontent.com/lord-alfred/ipranges/main/oracle.json"
      #   type: "json"

      # --- CDN and Edge Providers (Only Cloudflare Active) ---
      # - name: "trusted_cloudflare_ips"
      #   sync_from: "https://raw.githubusercontent.com/lord-alfred/ipranges/main/cloudflare.json"
      #   type: "json"

      # - name: "trusted_fastly_ips"
      #   sync_from: "https://raw.githubusercontent.com/lord-alfred/ipranges/main/fastly.json"
      #   type: "json"

      # - name: "trusted_stackpath_ips"
      #   sync_from: "https://raw.githubusercontent.com/lord-alfred/ipranges/main/stackpath.json"
      #   type: "json"

      # - name: "trusted_akamai_ips"
      #   sync_from: "https://raw.githubusercontent.com/lord-alfred/ipranges/main/akamai.json"
      #   type: "json"

      # --- Security and Anti-abuse Lists ---
      - name: "bad_ips"
        sync_from: "https://github.com/stamparm/ipsum/raw/refs/heads/master/levels/3.txt"
        type: "text"
      
    notifications:
      webhook: "https://yet-another-webhook-url.com"
